Update queue.js
AscariA10/homeCinemaProject pull request #2
Opened 2023-01-26 14:18 UTC by NaTaLiaMoSKV

Я создала класс Queue, в котором есть функции для работы с локальным хранилищем. В хранилище сохраняется один объект с ключом 'Queue' и значением в виде массива объектов (объект - это фильм). В классе есть функция добавления нового фильма в начало массива объектов (чтобы при прорисовке карточек первыми были те фильмы, которые добавлялись в очередь совсем недавно), функция удаления фильма из массива и функция обновления локального хранилища. Переменная length нужна для пагинации.

2023-01-26 22:19 UTC, AscariA10 requested changes
Я оставил несколько комментариев, исключительно по поводу наименования функций и переменных, сейчас не совсем понимаю последнюю функцию, давай завтра обсудим. В целом по логике все сделано хорошо.

2023-01-27 00:02 UTC, NaTaLiaMoSKV commented
> Я оставил несколько комментариев, исключительно по поводу наименования функций и переменных, сейчас не совсем понимаю последнюю функцию, давай завтра обсудим. В целом по логике все сделано хорошо.

2023-01-27 07:53 UTC, AscariA10 commented on src/js-blocks/queue.js
> +const qStr = 'Queue';
Имена констант, которые не меняются пишем в ВОТ_В_ТАКОМ_СТИЛЕ, также имя для переменной будет лучше QUEUE_LOCAL_STORAGE_KEY, или подобное

2023-01-27 07:54 UTC, AscariA10 commented on src/js-blocks/queue.js
> +        this.queueArray = [];
мне кажется имя лучше queueList, но это не критично

2023-01-27 07:55 UTC, AscariA10 commented on src/js-blocks/queue.js
> +    addMovieToQueue(movie) {
addMovieToQueueList

2023-01-27 07:56 UTC, AscariA10 commented on src/js-blocks/queue.js
> +        this.queueArray.splice(0, 0, movie);
тут есть метод unshift(), но можно и так оставить

2023-01-27 07:59 UTC, AscariA10 commented on src/js-blocks/queue.js
> +        } else console.log('can\'t find the movie to delete');
для уведомлений уже подключена notlify, можно использовать

2023-01-27 08:02 UTC, AscariA10 commented on src/js-blocks/queue.js
> +    updateLocalStorage() {
тут не совсем понимаю (из названия) что мы обновляем, если Queue, то лучше написать updateQueueList или в таком стиле

2023-01-27 08:07 UTC, AscariA10 commented on src/js-blocks/queue.js
> +    getItem(){
Тоже самое, из названия не совсем понятно что получаем, если массив фильмов которые храняться то наверное лучше чтото типа getQueueList или getQueuedMovies

2023-01-27 08:11 UTC, AscariA10 requested changes
В этот раз вроде комментарии закрепил, я предложил альтернативы названий для более простого восприятия при чтении. Не обязательно использовать именно те что я предлагаю можно использовать свои. Такой вопрос, а последние 2 функции можно перевести на методы класса get и set?

2023-01-27 14:16 UTC, AscariA10 approved these changes
Хорошая работа

2023-01-27 14:17 UTC, merged