Feature  card render
AscariA10/homeCinemaProject pull request #3
Opened 2023-01-27 06:04 UTC by YuliaKorchahina

Привіт. 
Зі стилями велика біда, буду сьогодні цим займатися. на них не дивися)
Закидаю, щоб ти подивився тільки логіку, щоб мати від чого відштовхуватися.

2023-01-27 13:20 UTC, AscariA10 commented on src/partials/main-index-page.html
> +    <!-- рендер картки -->
комеенти тільки ENGLISH обов'язкова вимога ментора, надалі не буду вказувати, але будь-ласка виправ

2023-01-27 13:56 UTC, AscariA10 commented on src/js-blocks/card-draw.js
> +  const average = Math.round(vote_average);
думаю краще додати tofixed, щоб було 1 чи 2 цифри
https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Number/toFixed#%D0%BF%D1%80%D0%B8%D0%BC%D0%B5%D1%80%D1%8B

2023-01-27 13:58 UTC, AscariA10 commented on src/js-blocks/card-draw.js
> +  return `<div class="card-item">
я думаю краще все таки це обгорнути списком, та додавати <li> в ul

2023-01-27 13:59 UTC, AscariA10 commented on src/js-blocks/card-draw.js
> +        <p class="card-ganres"></p>
genres, якщо в однині то genre

2023-01-27 14:01 UTC, AscariA10 commented on src/sass/_main-index-page.scss
> +/* ------------------------common ------------------------*/
я знаю що ти зараз працюєш над стилями, тому ось ці commonStyles, просто перепиши в файл common

2023-01-27 14:04 UTC, AscariA10 requested changes
Все добре, відмітив незначні виправлення, єдине питання яке не зовсім розумію це отримання картинки для фільму, я в тебе сьогодні про це запитаю

2023-01-27 14:27 UTC, AscariA10 requested changes
Чекаю вже на новий з усіма виправленнями та правками)

2023-01-27 15:05 UTC, YuliaKorchahina commented on src/partials/main-index-page.html
> +    <!-- рендер картки -->
ок

2023-01-27 15:05 UTC, YuliaKorchahina commented on src/js-blocks/card-draw.js
> +  const average = Math.round(vote_average);
помітила і  вже виправила, в новому пуші це вже є, пришлю на реквест

2023-01-27 15:05 UTC, YuliaKorchahina commented on src/js-blocks/card-draw.js
> +  return `<div class="card-item">
помітила і  вже виправила, в новому пуші це вже є, пришлю на реквест

2023-01-27 15:05 UTC, YuliaKorchahina commented on src/js-blocks/card-draw.js
> +        <p class="card-ganres"></p>
окей

2023-01-27 15:06 UTC, YuliaKorchahina commented on src/js-blocks/card-draw.js
> +        <p class="card-ganres"></p>
але по макету там не один жанр виводиться

2023-01-27 15:06 UTC, YuliaKorchahina commented on src/sass/_main-index-page.scss
> +/* ------------------------common ------------------------*/
я те все видалила, то збірна солянка всього підряд

2023-01-27 19:23 UTC, AscariA10 commented on src/partials/main-index-page.html
> +    <ul class="gallery-item list"></ul>
не зовсім розумію класс list...це дня обнулення?

2023-01-27 19:31 UTC, AscariA10 commented on src/sass/_main-index-page.scss
> +.list {
Я не зовсім розумію навіщо робити дод. класс на обнулення, чи не краще це робити через 
ul
{list-style: none;
  padding: 0;}

2023-01-27 19:35 UTC, AscariA10 requested changes
Зараз виникають деякі питання по стилям, давай зв'яжемося для корегування їх назв та місця написання, по js питань нема, якщо дійдемо згоди щодо стилів, то я апрувну, потім просто переробимо назви та грамотно розмістимо у сасс, а у той час інші участники зможуть вже малювати

2023-01-28 11:28 UTC, AscariA10 approved these changes
Приймаю

2023-01-28 11:28 UTC, merged