without local
AscariA10/homeCinemaProject pull request #6
Opened 2023-01-27 17:56 UTC by VictoriaSzn

2023-01-27 21:26 UTC, AscariA10 commented on src/js-blocks/modal-window.js
> +const watchBtnRef = document.querySelector('.but_watced');
but_watched, не совсем правильное название класса, 
1. через дефис 
2. but не совсем хорошее сокращение, лучше btn
3. watced не правильно watched
4. css селекторы пишутся через дефис, btn-watched
и это касается всего документа

2023-01-27 21:31 UTC, AscariA10 commented on src/js-blocks/modal-window.js
> +watchBtnRef.insertAdjacentHTML("afterbegin", "<span class='add_watch'>add to Watched </span>");
это достаточно грубый метод, и наверное не совсем правильный, куда проще у кнопок просто менять textContent, прикрепляю  ссылку на урок

https://www.edu.goit.global/uk/learn/5867983/2294/2305/textbook

Везде, где делала кнопки через insertAdjacentHTML 
 стоит переделать через textContent

2023-01-27 21:55 UTC, AscariA10 commented on src/partials/modal-window-index-page.html
> +  <div class="modal">
modal_window

2023-01-27 21:56 UTC, AscariA10 commented on src/partials/modal-window-index-page.html
> +            <button type="button" class="btn_choice but_queue">
В кнопках пустота, думаю стоит пересмотреть логику создания и работы с ними

2023-01-27 22:01 UTC, AscariA10 requested changes
Я просмотрел, однозначно много сделано, но надо немного изменить подход к кнопкам и разобратся почему они так работают, также нужно немного переименовывать классы, давай завтра , когда у тебя будет возможность, созвонимся и обсудим эти элементы. 
Каркас макета уже готов, это хорошо , просто немного доработаем)

2023-01-28 12:22 UTC, VictoriaSzn commented on src/js-blocks/modal-window.js
> +const watchBtnRef = document.querySelector('.but_watced');
название класса исправила, по BEM весь док проверю позже

2023-01-28 12:23 UTC, VictoriaSzn commented on src/js-blocks/modal-window.js
> +watchBtnRef.insertAdjacentHTML("afterbegin", "<span class='add_watch'>add to Watched </span>");
изменила, на trxtContent

2023-01-28 12:23 UTC, VictoriaSzn commented on src/partials/modal-window-index-page.html
> +  <div class="modal">
+

2023-01-28 12:23 UTC, VictoriaSzn commented on src/partials/modal-window-index-page.html
> +            <button type="button" class="btn_choice but_queue">
ok

2023-01-28 20:32 UTC, AscariA10 approved these changes
Прекрасно, на данный момент принимаю, нюансы со стилями будем доделывать по ходу

2023-01-28 20:50 UTC, merged