Add header for library css and markup
AscariA10/homeCinemaProject pull request #9
Opened 2023-01-27 20:58 UTC by VladyslavLiapko

2023-01-27 22:41 UTC, AscariA10 commented on src/partials/header-library-page.html
> +      <div class="header__buttons">
тут має бути список із 2х кнопок

2023-01-27 22:42 UTC, AscariA10 requested changes
Написав у тексті

2023-01-28 18:21 UTC, VladyslavLiapko commented on src/partials/header-library-page.html
> +      <div class="header__buttons">
Done

2023-01-28 21:50 UTC, AscariA10 approved these changes
Зараз приймаю , але треба буде стилі доробити, також треба буде доставити посилання на сторінки, але зараз головне обробка кнопок.

2023-01-28 21:50 UTC, merged